In [1]:
import numpy as np 


In [2]:
import numpy as np

# --- 1. THE BASICS: CREATION ---
# 1. Create a 1D array
arr1 = np.array([1, 2, 3])

# 2. Create a 2D array (Matrix)
arr2 = np.array([[1, 2], [3, 4]])

# 3. Array of zeros (3 rows, 4 cols)
zeros = np.zeros((3, 4))

# 4. Array of ones
ones = np.ones((2, 2))

# 5. Constant value array
full = np.full((2, 2), 7)

# 6. Range of values (Start, Stop, Step)
range_arr = np.arange(0, 10, 2)

# 7. Evenly spaced values
linspace = np.linspace(0, 1, 5)

# 8. Identity matrix
eye = np.eye(3)

# 9. Random floats (0 to 1)
rand = np.random.rand(3, 2)

# 10. Random integers (low, high, size)
randint = np.random.randint(0, 100, (3, 3))

# --- 2. INSPECTION & ATTRIBUTES ---
# 11. Array shape
shape = arr2.shape

# 12. Number of dimensions
dims = arr2.ndim

# 13. Total number of elements
size = arr2.size

# 14. Data type
dtype = arr1.dtype

# --- 3. MANIPULATION ---
# 15. Reshape (must match total size)
reshaped = np.arange(6).reshape((2, 3))

# 16. Flatten to 1D
flat = arr2.flatten()

# 17. Transpose
transposed = arr2.T

# 18. Vertical stack
v_stack = np.vstack(([1, 2], [3, 4]))

# 19. Horizontal stack
h_stack = np.hstack(([1, 2], [3, 4]))

# 20. Split an array
split = np.array_split(np.arange(6), 3)

# 21. Append values
appended = np.append(arr1, [4, 5])

# 22. Delete index 1
deleted = np.delete(arr1, 1)

# --- 4. MATHEMATICS & STATS ---
# 23. Element-wise addition
add = np.add(arr1, arr1)

# 24. Element-wise square root
sq = np.sqrt(arr1)

# 25. Matrix Multiplication (Dot product)
dot = np.dot(arr2, arr2)

# 26. Sum of all elements
total = arr1.sum()

# 27. Sum along axis (columns)
col_sum = arr2.sum(axis=0)

# 28. Mean
avg = arr1.mean()

# 29. Median
med = np.median(arr1)

# 30. Standard Deviation
std = np.std(arr1)

# 31. Cumulative Sum
cum_sum = np.cumsum(arr1)

# --- 5. INDEXING & SLICING ---
# 32. Simple slicing [start:stop:step]
slice1 = arr1[1:3]

# 33. Multi-dimensional slicing
# [rows, cols] -> Get all rows, but only the 2nd column
slice2 = arr2[:, 1]

# 34. Boolean Indexing (Filtering)
filtered = arr1[arr1 > 1]

# 35. Fancy Indexing (Select specific indices)
fancy = arr1[[0, 2]]

# --- 6. ADVANCED LOGIC & SORTING ---
# 36. Where (Condition, Value if True, Value if False)
where_logic = np.where(arr1 > 1, 10, 0)

# 37. Sort array
sorted_arr = np.sort(np.array([3, 1, 2]))

# 38. Get indices that would sort the array
sort_idx = np.argsort(arr1)

# 39. Find unique elements
unique = np.unique([1, 1, 2, 3, 3])

# 40. Clip values (Min, Max)
clipped = np.clip(arr1, 1, 2)

# --- 7. LINEAR ALGEBRA (LINALG) ---
# 41. Matrix Inverse
inv = np.linalg.inv(np.array([[1, 2], [3, 4]]))

# 42. Matrix Determinant
det = np.linalg.det(arr2)

# 43. Eigenvalues and Eigenvectors
eig_val, eig_vec = np.linalg.eig(arr2)

# 44. Solve linear system Ax = b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)

# --- 8. EXPERT & MISC ---
# 45. Broadcast scalar to array
broadcast = arr1 + 10

# 46. Copy array (Deep copy)
arr_copy = arr1.copy()

# 47. Check for NaN (Not a Number)
has_nan = np.isnan(np.array([1, np.nan]))

# 48. Replace NaN with 0
nan_fix = np.nan_to_num(np.array([1, np.nan]))

# 49. Save array to disk
np.save('my_array.npy', arr1)

# 50. Load array from disk
loaded_arr = np.load('my_array.npy')

In [3]:
# one D  array 

arr=np.array([1,2,3,34,55,67,3,3,6])
arr

array([ 1,  2,  3, 34, 55, 67,  3,  3,  6])

In [4]:
# specific index printing 
print(arr[2])

3


In [5]:
# printing all the array 
print (arr)

[ 1  2  3 34 55 67  3  3  6]


In [6]:
# using by for loop

for i in range(len(arr)):
    print(arr[i])



1
2
3
34
55
67
3
3
6


In [7]:
# using by slice 
# this will split the array and give the space b/w the num of the 2 digit 

#[start ind:upto index:diff b/w]
print(arr[0:11:2])

[ 1  3 55  3  6]


In [8]:
# revrese printing 

print(arr[::-1])


[ 6  3  3 67 55 34  3  2  1]


In [9]:
# addition of the in the arr  with each element 

print(arr+5)



[ 6  7  8 39 60 72  8  8 11]


In [10]:
# array sorting 

arr.sort()
arr

array([ 1,  2,  3,  3,  3,  6, 34, 55, 67])

In [11]:
arr2=np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [14]:
arr3=np.ones(5)

arr3

array([1., 1., 1., 1., 1.])

In [18]:
##2d array 
arr2D=np.array([[6,8,3,4],[7,5,3,4]]) 

arr2D


array([[6, 8, 3, 4],
       [7, 5, 3, 4]])

In [20]:
arr2D.sort()

arr2D

array([[3, 4, 6, 8],
       [3, 4, 5, 7]])

In [ ]:
for i in range(len(arr2D)):
    for j in range(len(arr2D[i])):
        print(arr2D[i][j], end=" ")
        print()

    print("\nMatrix form:")
    print(arr2D)

3
4
6
8
3
4
5
7
